Credentials:
  loginURL: ""
  Username: ""
  Password: ""
ALTanks:
  tanks:
    - name: ""
      tankID: ""
      delID: ""
    - name: ""
      tankID: ""
      delID: ""
SPIs:
  - ID: ""
    name: ""