version: '3'
services:
  tank-scraper:
    build: ./configuration/tank-scraper/
    hostname: tank-scraper
    container_name: tank-scraper
    restart: unless-stopped
    volumes:
    - "./logs:/app/logs"
    - "/etc/localtime:/etc/localtime:ro"

  # Capture AirLiquide tank metrics
  SCANS-Tanks:
    image: dalongrong/grok-exporter
    hostname: SCANS-Tanks
    container_name: SCANS-Tanks
    restart: unless-stopped
    volumes:
    - "./logs/tanks:/opt/logs"
    - "./configuration/grok/tank.yml:/grok/config.yml"
    depends_on:
    - tank-scraper
    ports:
    - "9149:9149"
    expose:
    - "9149"

  # Capture AirLiquide spi metrics
  SCANS-Spi:
    image: dalongrong/grok-exporter
    hostname: SCANS-Spi
    container_name: SCANS-Spi
    restart: unless-stopped
    volumes:
    - "./logs/spi:/opt/logs"
    - "./configuration/grok/spi.yml:/grok/config.yml"
    depends_on:
    - tank-scraper
    ports:
    - "9150:9150"
    expose:
    - "9150"
