{
 "title": "CRMN Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Compute summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workstation Summary",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "label_replace(up{job=\"WorkstationMetrics\"}, \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_time_seconds{job=\"WorkstationMetrics\"} - node_boot_time_seconds{job=\"WorkstationMetrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (instance) (node_hwmon_temp_celsius{job=\"WorkstationMetrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workstation CPU Load",
   "type": "timeseries",
   "description": "Inverse of CPU idle",
   "gridPos": { "h": 6, "w": 11, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(1-sum by(instance) (irate(node_cpu_seconds_total{job=\"WorkstationMetrics\", mode=\"idle\"}[2m15s])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"WorkstationMetrics\"}[2m15s]))), \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_hostname}}"
    }
   ]
  },
  {
   "title": "Server Room Air Temp",
   "type": "stat",
   "description": "Based on inlet air temperature to CRMN server box",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dell_hw_chassis_temps_reading{component=\"System_Board_Inlet_Temp\"}",
     "legendFormat": "RoomTemp"
    }
   ]
  },
  {
   "title": "RAID Free Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/share\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workstation RAM load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(100- (node_memory_MemAvailable_bytes{job=\"WorkstationMetrics\"} * 100) / node_memory_MemTotal_bytes{job=\"WorkstationMetrics\"}, \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_hostname}}"
    }
   ]
  },
  {
   "title": "RAID Array Disks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(count_values(\"dell_hw_storage_pdisk_status\", dell_hw_storage_pdisk_status != 1)) -18)",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(dell_hw_storage_pdisk_status)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Compressor Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    { "title": "HTML Panel", "type": "aidanmountford-html-panel", "gridPos": { "h": 10, "w": 4, "x": 0, "y": 24 }, "format": "short" }
   ]
  },
  {
   "title": "Spectrometer Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true
  },
  {
   "title": "CRMN Server Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thermals",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "dell_hw_chassis_temps_reading{job=\"RAIDMetrics\"}",
       "legendFormat": "{{component}}"
      }
     ]
    },
    {
     "title": "Network usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 13, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{device=\"eth0\"}[5m]) * 8 * 8",
       "legendFormat": "{{device}}: received"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\"}[5m])",
       "legendFormat": "{{device}}: sent"
      }
     ]
    }
   ]
  }
 ]
}