Credentials:
  loginURL: "https://mygas.airliquide.fr/user/login?destination=node/73078"
  Username: "james.tolchard@ens-lyon.fr"
  Password: "jamesCRMNairliquide5082*"
ALTanks:
  tanks:
    - name: "FLOXAL"
      tankID: "a781fc41-8e91-40d4-bd23-8aaf29f09fc5"
      delID: "7878512c-0f3a-486e-a554-0ff318e12990"
    - name: "CRMN"
      tankID: "27a796e2-d059-4b11-a91f-108f67758385"
      delID: "e399a8d3-a5e6-461f-8464-034454d39af5"
SPIs:
  - ID: "5c815804-f70e-4f38-913c-baf8e4a03416"
    name: "spi1"