version: '3'
services:

# Scrape helium and nitrogen levels from the HLMU web interface
  scans-hlmu:
    privileged: true
    build: ./configuration/read_HLMU/
    hostname: SCANS-hlmu
    container_name: SCANS-hlmu
    restart: unless-stopped
    volumes:
    - "./logs:/app/logs"

# Scrape spectrometer metrics from mounted log files
  # Capture helium metrics
  scans-helium_gyr:
    privileged: true
    image: dalongrong/grok-exporter
    hostname: SCANS-Helium_gyr
    container_name: SCANS-Helium_gyr
    restart: unless-stopped
    volumes:
    - "./logs:/opt/logs"
    - "./configuration/grok/hlmu/helium.yml:/grok/config.yml"
    ports:
    - "9152:9152"
    expose:
    - "9152"
  # Capture nitrogen metrics
#  scans-nitrogen_gyr:
#    privileged: true
#    image: dalongrong/grok-exporter
#    hostname: SCANS-Nitrogen_gyr
#    container_name: SCANS-Nitrogen_gyr
#    restart: unless-stopped
#    volumes:
#    - "./logs:/opt/logs"
#    - "./configuration/grok/hlmu/nitrogen.yml:/grok/config.yml"
#    ports:
#    - "9153:9153"
#    expose:
#    - "9153"  
