# SCANS docker-compose global config
version: '3'
services:
  # Report fundamental computer-useage metrics
  node-exporter:
    image: prom/node-exporter:latest
    hostname: node-exporter
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(boot|proc|root|dev|run|sys|var/lib/docker/.+)($$|/)'
      - '--collector.filesystem.ignored-fs-types=(rootfs|rpc_pipefs)'
    ports: 
      - "9100:9100"
    expose:
      - "9100"
  # Scrape Dell poweredge iDrac hardware metrics
  dellhw_exporter:
    image: quay.io/galexrt/dellhw_exporter:v1.12.2
    hostname: dellhw_exporter
    container_name: dellhw_exporter
    privileged: true
    restart: unless-stopped
    ports: 
    - "9137:9137"
    expose:
      - "9137"