# SCANS docker-compose global config
version: '3'
services:
  # Scrape fundamental computer-useage metrics
  node-exporter:
    privileged: true
    image: prom/node-exporter:latest
    hostname: node-exporter
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports: 
      - "9100:9100"
    expose:
      - "9100"
  # Scrape cryogen metrics from mounted log files
  grok:
    privileged: true
    image: dalongrong/grok-exporter
    hostname: grok
    container_name: grok
    restart: unless-stopped
    volumes: 
    - "./example:/opt/example"
    - "./configuration/grok.yml:/grok/config.yml"
    ports: 
    - "9144:9144"
    expose:
      - "9144"