version: '3'
services:
  scans-env_read:
    build: ./configuration/Client-EnvSensor
    hostname: scans-env_read
    container_name: scans-env_read
    restart: unless-stopped
    volumes:
    - "./logs:/app/logs"
    - "/etc/localtime:/etc/localtime:ro"

  # Scrape the metrics from the retrieved logs: UPS
  scans-env_report:
    image: dalongrong/grok-exporter
    hostname: scans-env_report
    container_name: scans-env_report
    restart: unless-stopped
    volumes:
    - "./logs/:/opt/logs"
    - "./configuration/grok/env.yml:/grok/config.yml"
    depends_on:
    - scans-env_read
    ports:
    - "9155:9155"
    expose:
    - "9155"